embeddings {
  tensor_name: "Latent Space, Epoch 5:7999.0"
  tensor_path: "7999.0/Latent Space, Epoch 5\\tensors.tsv"
}
embeddings {
  tensor_name: "Latent Space, Epoch 10:15999.0"
  tensor_path: "15999.0/Latent Space, Epoch 10\\tensors.tsv"
}
embeddings {
  tensor_name: "Latent Space, Epoch 15:23999.0"
  tensor_path: "23999.0/Latent Space, Epoch 15\\tensors.tsv"
}
embeddings {
  tensor_name: "Latent Space, Epoch 20:31999.0"
  tensor_path: "31999.0/Latent Space, Epoch 20\\tensors.tsv"
}
embeddings {
  tensor_name: "Latent Space, Epoch 25:39999.0"
  tensor_path: "39999.0/Latent Space, Epoch 25\\tensors.tsv"
}
embeddings {
  tensor_name: "Latent Space, Epoch 30:47999.0"
  tensor_path: "47999.0/Latent Space, Epoch 30\\tensors.tsv"
}
embeddings {
  tensor_name: "Latent Space, Epoch 35:55999.0"
  tensor_path: "55999.0/Latent Space, Epoch 35\\tensors.tsv"
}
embeddings {
  tensor_name: "Latent Space, Epoch 40:63999.0"
  tensor_path: "63999.0/Latent Space, Epoch 40\\tensors.tsv"
}
embeddings {
  tensor_name: "Latent Space, Epoch 45:71999.0"
  tensor_path: "71999.0/Latent Space, Epoch 45\\tensors.tsv"
}
embeddings {
  tensor_name: "Latent Space, Epoch 50:79999.0"
  tensor_path: "79999.0/Latent Space, Epoch 50\\tensors.tsv"
}
embeddings {
  tensor_name: "Latent Space, Epoch 55:87999.0"
  tensor_path: "87999.0/Latent Space, Epoch 55\\tensors.tsv"
}
embeddings {
  tensor_name: "Latent Space, Epoch 60:95999.0"
  tensor_path: "95999.0/Latent Space, Epoch 60\\tensors.tsv"
}
embeddings {
  tensor_name: "Latent Space, Epoch 65:103999.0"
  tensor_path: "103999.0/Latent Space, Epoch 65\\tensors.tsv"
}
embeddings {
  tensor_name: "Latent Space, Epoch 70:111999.0"
  tensor_path: "111999.0/Latent Space, Epoch 70\\tensors.tsv"
}
